# Generated by Django 3.0.5 on 2020-05-25 11:03

import authentication.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseInfectionStatus',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('infection_status', models.CharField(max_length=250)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistoricLocation',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
                ('timestamp', models.CharField(max_length=15)),
                ('infection_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DiseaseInfectionStatus')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenDiseaseRelation',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('historic_locations', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('wellness', models.CharField(choices=[('healthy', 'HEALTHY'), ('healthy_but_susceptible', 'HEALTHY_BUT_SUSCEPTIBLE'), ('not_infected', 'NOT_INFECTED'), ('immunized', 'IMMUNIZED'), ('infected_with_symptom', 'INFECTED_WITH_SYMPTOM'), ('infected_without_symptom', 'INFECTED_WITHOUT_SYMPTOM')], default='healthy', max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Citizen')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disease')),
            ],
        ),
    ]
