# Generated by Django 3.0.5 on 2020-05-31 14:58

import authentication.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0002_auto_20200525_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSeverityLevel',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('color_code', models.CharField(max_length=12)),
                ('no_of_cases', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.DataEntryAdminRegion')),
            ],
        ),
    ]
