# Generated by Django 3.0.5 on 2020-05-31 20:48

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200531_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessmentRecommendation',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('recommendation', models.CharField(max_length=250)),
                ('recommendation_detail', models.TextField()),
                ('point_upper_limit', models.FloatField()),
                ('point_lower_limit', models.FloatField()),
            ],
        ),
    ]
