# Generated by Django 3.0.5 on 2020-06-03 05:52

import authentication.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0006_selfscreeningquestion_wellnessstatusoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizendiseaserelation',
            name='wellness',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='CitizenLocationSync',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Citizen')),
            ],
        ),
    ]
