# Generated by Django 3.0.5 on 2020-06-11 06:47

import authentication.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200611_0647'),
        ('core', '0007_auto_20200603_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDataEntryAdminRegion',
            fields=[
            ],
            options={
                'verbose_name': 'data entry admin region',
                'verbose_name_plural': 'data entry admin regions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.dataentryadminregion',),
        ),
        migrations.CreateModel(
            name='ProxyFCMPushNotificationRegistrationToken',
            fields=[
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.fcmpushnotificationregistrationtoken',),
        ),
        migrations.CreateModel(
            name='ProxyRegion',
            fields=[
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.region',),
        ),
        migrations.CreateModel(
            name='CitizenPushNotifications',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('CONTACT-TRACING', 'Contact tracing'), ('HOTSPOT-PROXIMITY', 'Hotspot proximity'), ('ANNOUNCEMENT', 'General announcement')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Citizen')),
            ],
        ),
    ]
