# Generated by Django 3.0.5 on 2020-06-11 11:40

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_citizenpushnotifications_proxydataentryadminregion_proxyfcmpushnotificationregistrationtoken_proxyre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumberWhitelist',
            fields=[
                ('id', models.CharField(default=authentication.utils.hex_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('mobile_number', models.CharField(max_length=18, unique=True)),
            ],
        ),
    ]
