# Generated by Django 3.0.5 on 2020-06-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_citizenhistoriclocationdiseaserelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizendiseaserelation',
            name='historic_locations',
        ),
    ]
