# Generated by Django 3.0.5 on 2020-06-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_citizenlocationsync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenhistoriclocationdiseaserelation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patienthistoriclocation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
