# Generated by Django 3.0.5 on 2020-06-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200611_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenhistoriclocationdiseaserelation',
            old_name='timestamp',
            new_name='recorded_date_time',
        ),
        migrations.RenameField(
            model_name='patienthistoriclocation',
            old_name='timestamp',
            new_name='recorded_date_time',
        ),
    ]
