# Generated by Django 3.0.5 on 2020-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='iam_user_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
