# Generated by Django 3.0.5 on 2020-06-09 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200604_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMPushNotificationRegistrationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('application_id', models.CharField(blank=True, help_text='Opaque application identity, should be filled in for multiple key/certificate access', max_length=64, null=True, verbose_name='Application ID')),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='ANDROID_ID / TelephonyManager.getDeviceId() (always as hex) / UDID / UIDevice.identifierForVendor()', max_length=1024, null=True, verbose_name='Device ID')),
                ('registration_id', models.TextField(verbose_name='Registration ID')),
                ('cloud_message_type', models.CharField(choices=[('FCM', 'Firebase Cloud Message'), ('GCM', 'Google Cloud Message')], default='GCM', help_text='You should choose FCM or GCM', max_length=3, verbose_name='Cloud Message Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GCM device',
            },
        ),
    ]
