# Generated by Django 3.0.5 on 2020-06-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200611_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='is_profile_complete',
            new_name='is_location_sync_enabled',
        ),
    ]
